config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  get "/health", to: ->(env) { [204, {}, [""]] }
  post "/practices/:id/drills", to: "practices#add_drill"
  delete "/practices/:id/drills/:drill_id", to: "practices#remove_drill"
  root "dashboard#show"

  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup

  resources :comments, only: [:create, :destroy]
  resources :appearances
  resources :drills
  resources :matches
  resources :players
  resources :practices
  resources :teams
  resources :users, only: [:create, :update, :show]

  resources :squads do
    resources :players
  end

  resources :libraries do
    resource :drills
  end
end

app/models/library.rb
# == Schema Information
#
# Table name: libraries
#
#  id         :uuid             not null, primary key
#  user_id    :uuid             not null
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Library < ApplicationRecord
  include AccessControlled
  include Commentable

  acts_as_taggable

  validates :name, presence: true

  belongs_to :user

  has_many :plays
  has_many :drills
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :ensure_enabled
  before_action :set_library, only: [:show, :update, :edit, :destory]

  def safe_params
    params.require(:library).permit(:name)
  end

  def index
    @pagy, @libraries = pagy Library.accessible_to(current_user)
  end

  def new
    @library = Library.new
    render template: "libraries/form"
  end

  def create
    @library = Library.create safe_params.merge(user: current_user)
    if @library.valid?
      current_user.access_controls.create(access_controlled: @library)
      flash[:success] = t("library.create.success")
      redirect_to @library
    else
      flash[:warning] = @library.errors.full_messages
      render template: "libraries/form"
    end
  end

  def edit
    render template: "libraries/form"
  end

  def update
    @library.update safe_params
    if @library.valid?
      flash[:success] = t("library.updated")
      redirect_to @library
    else
      flash[:warning] = @library.errors.full_messages
      render template: "libraries/form"
    end
  end

  protected

  def set_library
    @library = Library.accessible_to(current_user).find_by(id: params[:id])
    fail ActiveRecord::RecordNotFound unless @library
  end

  def ensure_enabled
    head :unauthorized unless Flipper.enabled?(:drills, current_user)
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_library.haml
= link_to library, class: [:cell, :library] do
    .cell-body
        .cell-byline= pluralize library.drills.count, Drill.model_name.human
        .cell-header= library.name

app/views/libraries/form.haml
= render PageHeader.new(title: Library.model_name.human) 
= form_with model: @library, builder: CoachNotebookFormBuilder do |form|
    = form.text_field :name 
    = form.submit

app/views/libraries/index.haml
= render PageHeader.new(title: Library.model_name.human.pluralize)
.page-list
    .page-item
        .gridx4
            = render(@libraries) || render(partial: 'application/empty')
            = link_to new_library_path, class: [:cell, :new] do 
                .cell-body= t("library.new")
    = render 'pagination'

app/views/libraries/show.haml
= render PageHeader.new(title: @library.name) do
    = link_to t("library.edit"), edit_library_path(@library), class: 'btn-secondary'
.page-list
    = render "tags", taggable: @library
    .page-item
        .gridx4
            = render @library.drills.accessible_to(current_user)
            = link_to new_library_drills_path(@library), class: [:cell, :new] do 
                .cell-body= t("drill.new")
    = render "comments", commentable: @library