config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  get "/health", to: ->(env) { [204, {}, [""]] }
  post "/practices/:id/drills", to: "practices#add_drill"
  delete "/practices/:id/drills/:drill_id", to: "practices#remove_drill"
  root "dashboard#show"

  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup

  resources :comments, only: [:create, :destroy]
  resources :appearances
  resources :drills
  resources :matches
  resources :players
  resources :practices
  resources :teams
  resources :users, only: [:create, :update, :show]

  resources :squads do
    resources :players
  end

  resources :libraries do
    resource :drills
  end
end

app/models/practice.rb
# == Schema Information
#
# Table name: practices
#
#  id          :uuid             not null, primary key
#  practice_at :datetime
#  squad_id    :uuid             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Practice < ApplicationRecord
  include AccessControlled
  include Commentable

  acts_as_taggable

  belongs_to :squad
  has_many :practice_drills
  has_many :drills, through: :practice_drills

  validates :practice_at, presence: true

  scope :future, -> { where("practice_at < ?", Time.now) }
  scope :past, -> { where("practice_at < ?", Time.now) }

  def rating
    practice_drills.map(&:rating).sum / practice_drills.count
  rescue
    0
  end

  def copy_drills_from(other_practice_id)
    if (@original_practice = Practice.find_by(id: other_practice_id))
      @original_practice.drills.each do |drill|
        practice_drills.create(drill: drill)
      end
    end
  end

  def past?
    practice_at < Time.now
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :ensure_enabled
  before_action :set_practice, only: [:edit, :update, :destroy, :show, :add_drill, :remote_drive]
  before_action :set_practices, only: [:edit, :new, :create, :update]
  before_action :set_libraries, only: [:edit, :new, :create, :update]
  before_action :set_drills, only: [:edit, :new, :create, :update, :show]
  before_action :set_squads, only: [:edit, :new, :create, :update]

  def safe_params
    params.require(:practice).permit(:practice_at, :copy_practice_id, :squad_id)
  end

  def index
    @pagy, @practices = pagy Practice.accessible_to(current_user)
  end

  def new
    if @libraries.empty?
      flash[:notice] = t("practice.libraries_empty")
      redirect_to new_library_path
    elsif @squads.empty?
      flash[:notice] = t("practice.squads_empty")
      redirect_to new_squad_path
    elsif @drills.empty?
      flash[:notice] = t("practice.drills_empty")
      redirect_to new_drill_path
    else
      @practice = Practice.new
      render template: "practices/form"
    end
  end

  def edit
    render template: "practices/form"
  end

  def create
    @practice = Practice.create(practice_at: safe_params[:practice_at], squad_id: safe_params[:squad_id])
    if @practice.valid?
      @practice.copy_drills_from(safe_params[:copy_practice_id])
      current_user.access_controls.create(access_controlled: @practice)
      flash[:success] = t("practice.create.success")
      redirect_to @practice
    else
      flash[:warning] = @practice.errors.full_messages
      render template: "practices/form"
    end
  end

  def update
    @practice.update(safe_params)
    if @practice.valid?
      flash[:success] = t("practice.update.success")
      redirect_to @practice
    else
      flash[:warning] = @practice.errors.full_messages
      render template: "practices/form"
    end
  end

  def destroy
    if @practice.delete
      flash[:success] = t("squad.delete.success")
    else
      flash[:warning] = @practice.errors.full_messages
    end
    redirect_to practices_path
  end

  def add_drill
    @practice.practice_drills.create(drill_id: params[:drill_id])
    redirect_to practice_path(@practice)
  end

  def remove_drill
    @practice.practice_drills.find_by(drill_id: params[:drill_id]).destroy
    redirect_to practice_path(@practice)
  end

  protected

  def set_practice
    @practice = Practice.accessible_to(current_user).find_by(id: params[:id])
    fail ActiveRecord::RecordNotFound unless @practice
  end

  def ensure_enabled
    head :unauthorized unless Flipper.enabled?(:drills, current_user)
  end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_practice.haml
= link_to practice, class: [:cell, :practice] do
    .cell-body
        .cell-byline= practice.squad
        .cell-header= l(practice.practice_at, format: :day_date)

app/views/practices/form.haml
= render PageHeader.new(title: Practice.model_name.human) 
= form_with model: @practice, builder: CoachNotebookFormBuilder do |form|
    = form.select :squad_id, @squads.map{|s| [s.name, s.id]}
    = form.datetime_field :practice_at
    = form.select :copy_practice_id, @practices.map{|p| [p.practice_at.to_s + " - " + p.drills.limit(5).map(&:name).to_sentence, p.id] }
    = form.submit

app/views/practices/index.haml
= render PageHeader.new(title: Practice.model_name.human.pluralize)
.page-list
    .page-item 
        .gridx4
            = render(@practices) || render(partial: 'application/empty')
            = link_to new_practice_path, class: [:cell, :new] do 
                .cell-body= t("practice.new")
    = render 'pagination'

app/views/practices/show.haml
= render PageHeader.new(title: l(@practice.practice_at, format: :day_date), subtitle: [@practice.squad.competition, @practice.squad.season, @practice.squad.name])
.page-list
    = render "tags", taggable: @practice
    - @practice.practice_drills.order(:position).each do |practice_drill| 
        .page-item
            %h3.page-heading= link_to practice_drill.drill.name, drill_path(practice_drill.drill)
            .byline= pluralize practice_drill.drill.duration_minutes, Drill.human_attribute_name(:minute) 
            = render "tags", taggable: practice_drill.drill
            = markdown practice_drill.drill.body
            = render Rating.new(rating: @practice.rating, url: "#") if @practice.past?
            - if practice_drill.variation
                %h4.page-heading.text-slate-500= Drill.human_attribute_name(:variation) 
                = practice_drill.variation
            %h4.text-neutral-500= Drill.human_attribute_name(:keys) 
            = practice_drill.drill.keys.to_sentence
            %h4.text-neutral-500= Drill.human_attribute_name(:goals) 
            = practice_drill.drill.goals.to_sentence
    - unless @practice.past?
        .page-item 
            = form_for "/practices/#{@practice.id}/drills", builder: CoachNotebookFormBuilder, html: { class: "items-center gap-2"}  do
                .col-span-2
                    = select_tag :drill_id, options_from_collection_for_select(@drills, :id, :name), class: "form-input"
                .col-span-1
                    = submit_tag t("drill.new.add_to_practice"), class: "btn-primary"
    = render "comments", commentable: @practice

app/views/practices/show.html.haml
= render PageHeader.new(title: l(@practice.practice_at, format: :day_date), subtitle: [@practice.squad.name, @practice.squad.season, @practice.squad.competition].compact.join(" | ")) do 
    = render Rating.new(rating: @practice.rating) if @practice.past?
.page-list
    - if @practice.review?
        .-mx-4.p-4.rounded-md.bg-slate-200
            .text-sm.font-bold= Drill.human_attribute_name(:review) 
            .text-sm= @practice.review
    - else 
        - if @practice.past?
            = form_for @practice, builder: CoachNotebookFormBuilder do |form|
                .mb-2
                    = form.text_area :review
                = form.submit "Save", class: "btn-primary"
    - @practice.practice_drills.order(:position).each do |practice_drill| 
        .main
            .sidebar
                .heading-1= link_to practice_drill.drill.name, drill_path(practice_drill.drill)
                .byline= pluralize practice_drill.drill.duration_minutes, Drill.human_attribute_name(:minute) 
                - practice_drill.drill.tags.each do |tag|
                    .tag= t("tags.#{tag}")
                - unless @practice.past?
                    = button_to "remove", "/practices/#{@practice.id}/drills/#{practice_drill.drill.id}", class: "btn-secondary", method: :delete
            .body
                = markdown practice_drill.drill.body
                = render Rating.new(rating: @practice.rating, url: "#") if @practice.past?
                - if practice_drill.variation?
                    .text-sm= practice_drill.variation 
                - if practice_drill.drill.keys?
                    .text-xs.text-slate-500= Drill.human_attribute_name(:keys) 
                    .text-sm= practice_drill.drill.keys.to_sentence
    - unless @practice.past?
        = form_tag "/practices/#{@practice.id}/drills", builder: CoachNotebookFormBuilder do
            = select_tag :drill_id, options_from_collection_for_select(current_user.drills, :id, :name), class: "form-input"
            = submit_tag t("drill.new"), class: "btn-primary"