config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  get "/health", to: ->(env) { [204, {}, [""]] }
  post "/practices/:id/drills", to: "practices#add_drill"
  delete "/practices/:id/drills/:drill_id", to: "practices#remove_drill"
  root "dashboard#show"

  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup

  resources :comments, only: [:create, :destroy]
  resources :appearances
  resources :drills
  resources :matches
  resources :players
  resources :practices
  resources :teams
  resources :users, only: [:create, :update, :show]

  resources :squads do
    resources :players
  end

  resources :libraries do
    resource :drills
  end
end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id         :uuid             not null, primary key
#  played_at  :datetime
#  opposition :string
#  result     :string
#  home_team  :boolean
#  team_id    :uuid             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Match < ApplicationRecord
  include AccessControlled
  include Commentable

  acts_as_taggable

  belongs_to :team

  has_many :appearances
  has_many :players, through: :appearances

  def to_s
    [home_team ? "vs" : "at", opposition].join(" ")
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :ensure_enabled
  before_action :set_match, only: [:edit, :update, :destroy, :show]
  before_action :set_teams, only: [:edit, :new, :create, :update]

  def safe_params
    params.require(:match).permit(:name, :team_id, :played_at, :opposition, :result, :home_team)
  end

  def index
    @pagy, @matches = pagy Match.accessible_to(current_user)
  end

  def new
    if @teams.empty?
      flash[:notice] = t("match.teams_empty")
      redirect_to new_team_path
    else
      @match = Match.new
      render template: "matches/form"
    end
  end

  def edit
    render template: "matches/form"
  end

  def create
    @match = Match.create(safe_params)
    if @match.valid?
      current_user.access_controls.create(access_controlled: @match)
      flash[:success] = t("match.create.success")
      redirect_to @match
    else
      flash[:warning] = @match.errors.full_messages
      render template: "matches/form"
    end
  end

  def update
    @match.update(safe_params)
    if @match.valid?
      flash[:success] = t("match.update.success")
      redirect_to @match
    else
      flash[:warning] = @match.errors.full_messages
      render template: "matches/form"
    end
  end

  def destroy
    if @match.delete
      flash[:success] = t("match.deleted")
    else
      flash[:warning] = @match.errors.full_messages
    end
    redirect_to matches_path
  end

  def set_match
    @match = Match.accessible_to(current_user).find_by(id: params[:id])
    fail ActiveRecord::RecordNotFound unless @match
  end

  def ensure_enabled
    head :unauthorized unless Flipper.enabled?(:matches, current_user)
  end
end

app/views/matches/_match.haml
= link_to match, class: [:cell, :match ] do 
    .cell-body
        .cell-byline= l(match.played_at, format: :day_date)
        .cell-header
            = match.home_team ? "vs" : "at"
            = match.opposition
        

app/views/matches/form.haml
= render PageHeader.new(title: Match.model_name.human) 
= form_with model: @match, builder: CoachNotebookFormBuilder do |form|
    = form.select :team_id, Team.accessible_to(current_user).map{|team| [team.name, team.id]}
    = form.datetime_field :played_at
    = form.text_field :opposition
    = form.text_field :result 
    = form.select :home_team, ["True", "False"]
    = form.submit

app/views/matches/index.haml
= render PageHeader.new(title: Match.model_name.human.pluralize)
.page-list
    .page-item 
        .gridx4
            = render(@matches) || render(partial: 'application/empty')
            = link_to new_match_path, class: [:cell, :new] do 
                .cell-body= t("match.new")
    = render 'pagination'

app/views/matches/show.haml
= render PageHeader.new( title: @match, subtitle: l(@match.played_at, format: :day_date) ) do
    = link_to t("match.edit"), edit_match_path(@match), class: 'btn-secondary'
.page-list
    = render "tags", taggable: @match
    - if @match.score_final
        .page-item
            - if !@match.forfeit 
                .gridx3.border.p-8.rounded.border-neutral-700
                    .text-center
                        %h3.text-2xl= @match.home_score
                        %h4.text-sm= @match.home_team ? @match.team : @match.opposition
                    .text-2xl.text-center
                        = @match.home_score > @match.away_score ? t("defeated") : t("lost_to")
                    .text-center
                        %h3.text-2xl= @match.away_score
                        %h4.text-sm= @match.home_team ? @match.opposition : @match.team
            - else 
                .text-2xl.text-center= t("match.forfeit_result")
    .page-item
        .page-title= Match.human_attribute_name(:lineup) 
        .gridx5
            = render @match.appearances.order(:starting_position)
            = link_to new_appearance_path(match_id: @match.id), class: [:cell, :new] do 
                .cell-body= t("appearance.new")
    .page-item 
        .page-title= Match.human_attribute_name(:gameplan) 
    .page-item 
        .page-title= Match.human_attribute_name(:review) 