config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  get "/health", to: ->(env) { [204, {}, [""]] }
  post "/practices/:id/drills", to: "practices#add_drill"
  delete "/practices/:id/drills/:drill_id", to: "practices#remove_drill"
  root "dashboard#show"

  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup

  resources :comments, only: [:create, :destroy]
  resources :appearances
  resources :drills
  resources :matches
  resources :players
  resources :practices
  resources :teams
  resources :users, only: [:create, :update, :show]

  resources :squads do
    resources :players
  end

  resources :libraries do
    resource :drills
  end
end

app/models/squad.rb
# == Schema Information
#
# Table name: squads
#
#  id          :uuid             not null, primary key
#  user_id     :uuid             not null
#  active      :boolean
#  name        :string
#  competition :string
#  season      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Squad < ApplicationRecord
  include AccessControlled

  belongs_to :user

  has_many :libraries
  has_many :players
  has_many :practices
  has_many :teams
  has_many :matches, through: :teams

  validates :name, presence: true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  before_action :ensure_enabled
  before_action :set_squad, only: [:edit, :update, :show, :destroy]

  def safe_params
    params.require(:squad).permit(:season, :name, :competition)
  end

  def index
    @pagy, @squads = pagy Squad.accessible_to(current_user)
  end

  def new
    @squad = Squad.new
    render template: "squads/form"
  end

  def edit
    render template: "squads/form"
  end

  def create
    @squad = Squad.create(safe_params.merge(user: current_user))
    if @squad.valid?
      current_user.access_controls.create(access_controlled: @squad)
      flash[:success] = t("squad.create.success")
      redirect_to @squad
    else
      flash[:warning] = @squad.errors.full_messages
      render template: "squads/form"
    end
  end

  def update
    @squad.update(safe_params)
    if @squad.valid?
      redirect_to @squad
    else
      flash[:warning] = @squad.errors.full_messages
      render template: "squads/form"
    end
  end

  def destroy
    if @squad.delete
      flash[:success] = t("squad.deleted")
    else
      flash[:warning] = @squad.errors.full_messages
    end
    redirect_to squads_path
  end

  protected

  def set_squad
    @squad = Squad.accessible_to(current_user).find_by(id: params[:id])
    fail ActiveRecord::RecordNotFound unless @squad
  end

  def ensure_enabled
    head :unauthorized unless Flipper.enabled?(:matches, current_user) || Flipper.enabled?(:drills, current_user)
  end
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/squads/_squad.haml
= link_to squad, class: [:cell, :squad] do
    .cell-body
        .cell-byline= squad.season 
        .cell-header= squad 

app/views/squads/form.haml
= render PageHeader.new(title: Squad.model_name.human) 
= form_with model: @squad, builder: CoachNotebookFormBuilder do |form|
    = form.text_field :name
    = form.text_field :competition
    = form.text_field :season
    = form.submit

app/views/squads/index.haml
= render PageHeader.new(title: Squad.model_name.human.pluralize)
.page-list
    .page-item
        .gridx4
            = render(@squads) || render(partial: 'application/empty')
            = link_to new_squad_path, class: [:cell, :new] do 
                .cell-body= t("squad.new")
    = render 'pagination'

app/views/squads/show.haml
= render PageHeader.new(title: @squad.name, subtitle: [@squad.season, @squad.competition]) do 
    = link_to(t("squad.edit"), edit_squad_path(@squad), class: "btn-primary")
.page-list    
    - if Flipper.enabled?(:drills, current_user)
        .page-item
            .page-title= Practice.model_name.human.pluralize
            .gridx4
                = render @squad.practices.accessible_to(current_user).order(:practice_at).where('practice_at > ?', Time.now)
                = link_to new_practice_path(squad_id: @squad), class: [:cell, :new] do 
                    .cell-body= t("drill.new")
    - if Flipper.enabled?(:matches, current_user)
        .page-item
            .page-title= Team.model_name.human.pluralize
            .gridx4
                = render @squad.teams.accessible_to(current_user)
                = link_to new_team_path(squad_id: @squad), class: [:cell, :new] do 
                    .cell-body= t("team.new")
        .page-item 
            .page-title= Player.model_name.human.pluralize
            .gridx4
                = render @squad.players.accessible_to(current_user)
                = link_to new_player_path(squad_id: @squad), class: [:cell, :new] do 
                    .cell-body= t("player.new")